name = "StatisticalProjections"
uuid = "165bcf3d-aa04-45f7-b691-acf9bd4168c1"
authors = ["Oliver Niehuis <oliver.niehuis@biologie.uni-freiburg.de> and contributors"]
version = "1.0.0-DEV"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
JLD2 = "0.5.13"
LinearAlgebra = "1.11.0"
Optim = "1.12.0"
Random = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.4"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
